version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./redirect_manager:/home/user/redirect_manager

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env

volumes:
  redirect_manager:
